### ISSUE TITLE
Documentation missing Bootstrap version

### ISSUE THREAD

**Issue by robcresswell** [dobromir-hristov/vuelidate-error-extractor#1]
Hey, neat little library; it would be great if the docs specified the supported bootstrap version in your examples. It isn't clear :)

**Comment by dobromir-hristov** [comment]
Will do later today.

**Comment by dobromir-hristov** [comment]
Do you mean I should note that I am supporting Bootstrap 3? I may do a Bootstrap 4 today as well :)

**Comment by robcresswell** [comment]
I don't mean to give you more to support; that's totally up to what you feel like doing. I just meant that it would be nice to make it clear that you are supporting 3 or 4 in the documentation. Currently it all says "supports Bootstrap and Foundation", but it would be nice if it said something like "supports Bootstrap 3 and Foundation 6", for example. FWIW, Bootstrap 4 is finally in Beta so should be much more stable from an API POV.

**Comment by dobromir-hristov** [comment]
Doing it as we speak :)

**Comment by dobromir-hristov** [comment]
Fixed #c2e4fd41d6a9105e298f9051feb2b060d46c4681

**Comment by robcresswell** [comment]
Awesome, thanks!
