### ISSUE TITLE
Multiply error are not delimited in a form-group template

### ISSUE THREAD

**Issue by aTanCS** [dobromir-hristov/vuelidate-error-extractor#13]
Is there any way to add a delimiter (eg. coma) for a single error template? Or to display them one per row? Or I have to create a custom template? When there are more than one error message, it does not look good. I understand that it says "single error extractor", but with a customizable delimiter it can be used with more errors per field.
See an example https://codesandbox.io/s/m5k91plwpp

**Comment by dobromir-hristov** [comment]
You have to handle that yourself. Yhe display is for the most part different for each project.
