### ISSUE TITLE
Bootstrap Vue and b-input-group prepend with FormGroup.vue

### ISSUE THREAD

**Issue by ghenry** [dobromir-hristov/vuelidate-error-extractor#14]
Hi all,

I'm struggling to get this to work like the plain example I've done. Not sure if it's a bv issue or my template. 

https://codesandbox.io/s/3v7620xwo6

Thanks.

**Comment by dobromir-hristov** [comment]
You are adding the slot-scope to the wrong component. Either add it to a wrapping template tag or to the **b-input-group**

https://gyazo.com/2fbcc064d6d652d20c2ae3ffd134e29b

**Comment by ghenry** [comment]
Perfect. Thanks. Working. Apologies for the noise.
