### ISSUE TITLE
localMessages *and* localAttributes

### ISSUE THREAD

**Issue by ghenry** [dobromir-hristov/vuelidate-error-extractor#15]
Hi,

I'm trying to figure out how to have local attributes names like you can set globally as I want friendly message for attribute names:

```
        <form-group
          class="col-md-6"
          name="telephoneNumber" 
          label="Telephone Number"
          font-awesome="fas fa-phone fa-rotate-90 fa-fw"
        >
          <b-form-input
            slot-scope="{ attrs, listeners }"
            v-bind="attrs"
            v-model="form.telephoneNumber"
            v-on="listeners" 
          /> 
        </form-group>
```
FYI, I've also had to add a prop to get bootstrap vue to take a font awesome class as a `<slot name="label"` won't work in the main form:
```

<template>
  <b-form-group
    :invalid-feedback="firstErrorMessage"
    :state="isValid"
  >
    <label><i :class="fontAwesome"/> {{ label }}</label>
    <slot
      :attrs="{ state: isValid }"
      :listeners="{ input: () => preferredValidator.$touch() }"
    />
  </b-form-group>
</template>
<script>
import { singleErrorExtractorMixin } from "vuelidate-error-extractor"

export default {
  name: "FormElement",
  extends: singleErrorExtractorMixin,
  props: {
    fontAwesome: {
      type: String,
      default: "fas fa-envelope fa-fw"
    }
  }
}
</script>
```

![screenshot_2018-10-15 gavin henry s profile - surevoip portal](https://user-images.githubusercontent.com/159608/46974216-58147e80-d0bb-11e8-8611-a5746d0d396b.png)

Here's my `src/main.js` snippet:

```
/* Actual messages presented to the user. Move to separate file and use i18n later */
const messages = {
  required: "Your {attribute} is required",
  email: "This is not a proper email address",
  minLength: "Your new password is not long enough",
  passwordComplexity:
    "Your new password is not complex enough. Please see above.",
  sameAsNewPassword:
    "Your confirmation password is not the same as your new password."
}

Vue.use(VuelidateErrorExtractor, {
  messages,
  attributes: {
    name: "Name",
    email: "Email",
    text: "Text",
    oldPassword: "old password",
    newPassword: "new password",
    confirmPassword: "password confirmation"
  }
})
```

Any tips?

**Comment by dobromir-hristov** [comment]
You want to be able to pass a set of local attributes per form-field? How is that easier than defining them globally, so you can re-use them?

You could overwrite `resolvedAttribute` computed property on your `FormElement` to check for a locally defined `attributes` prop. 

https://github.com/dobromir-hristov/vuelidate-error-extractor/blob/master/src/single-error-extractor-mixin.js#L56-L58

**Comment by ghenry** [comment]
:-)

We'll if I'm going to re-use them I'll define them globally, but if not, locally. I think it's valid to wish to do it both ways like you would with CSS, i.e. a local style applicable to that component or global, no?

Thanks, will try.

**Comment by ghenry** [comment]
Thanks for taking the time to look into this! Will have a play as I don't
like the way I'm doing it at the moment.

**Comment by dobromir-hristov** [comment]
@ghenry I was tweeking some things today and I remembered your issue. Why cant you use the `attribute` prop to pass an attribute per field? It has precedence over globally defined ones always.

**Comment by dobromir-hristov** [comment]
Can we close this?

**Comment by ghenry** [comment]
Yeah, you've provided a solution. I just need to implement it. Thanks!
