### ISSUE TITLE
npm dependency library get-value causes error with Vue CLI 3

### ISSUE THREAD

**Issue by jacobg** [dobromir-hristov/vuelidate-error-extractor#16]
vuelidate-error-extractor's transitive dependency `get-value` causes an error on Chrome 48 when built with Vue CLI 3 defaults, because it's non-transpiled es6 code.

I tried adding `get-value` to `transpileDependencies` in vue.config.js, but it causes another error in all browsers having to do with it being in common js format, as described here:  https://github.com/vuejs/vue-cli/issues/1248

Have you run into this issue? Are you able to just pull in get-value directly into your code as a native ES module, and transpile it?

**Comment by dobromir-hristov** [comment]
Just released a new version. Please give it a try.

**Comment by jacobg** [comment]
Awesome!! Thanks so much!

For academic purpose, I was able to get it working in the old version using this hack in vue.config.js:

```
// Need to convert get-value transitive dependency from common js module format to native es module format.
// Without this fix, Chrome 48 gets this error: "Block-scoped declarations (let, const, function, class) not yet supported outside strict mode"
// See this issue:  https://github.com/vuejs/vue-cli/issues/1248
replace({
  regex: 'module\\.exports =',
  replacement: 'export default',
  paths: [path.resolve(__dirname, 'node_modules/vuelidate-error-extractor/node_modules/get-value/index.js')],
  recursive: false,
  silent: true
})
```

**Comment by jacobg** [comment]
And the new version 2.2.3 works great! Thanks again!
