### ISSUE TITLE
Using dynamic value in validation messages

### ISSUE THREAD

**Issue by lorro** [dobromir-hristov/vuelidate-error-extractor#18]
Hi,

I'm wondering how to include a dynamic param in a specific validation message?
I'd like to use the minValue validation rule and had tried to setup my messages like this.

```js
import Vue from 'vue'

const messages = {
  required: Vue.i18n.translate('{attribute} can\'t be empty.'),
  email: Vue.i18n.translate('{attribute} should be a valid e-mail address.'),
  minValue: Vue.i18n.translate('{attribute} should be higher than {min}.')
}

export default messages
```

{min} however doesn't show anything. Is is actually possible this dynamic value in the message?
The validation rule is like this: ```minValue: minValue(0),```

Couldn't find anywhere which params are available to which validation rule, as the {attribute} param seems to work though. Ofc the value won't be always zero, so I need this to be dynamic :)

Greetings,
Thanks

**Comment by lorro** [comment]
Apparently it does work when I give the minValue rule a value that is different from 0.
```minValue: minValue(5)``` does work.

**Comment by dobromir-hristov** [comment]
It is a known bug, will fix it asapOn 28 Jan 2019 19:03, Laurent <notifications@github.com> wrote:Apparently it does work when I give the minValue rule a value that is different from 0.
minValue: minValue(5) does work.

**Comment by dobromir-hristov** [comment]
Oh you are using vuex-i18n, I have not prepared the plugin for it, though your approach may work, just not sure what will happen when languages get switched. 

Does the plugin pass the placeholders directly? Because VuelidateErrorExtractor does not know how to pass the params to it, so it just uses the returned raw string.

The bug you saw should be fixed and will be released shortly.

**Comment by dobromir-hristov** [comment]
Give it a try and close if it works now :)

**Comment by lorro** [comment]
Seems to work now. Thanks!
