### ISSUE TITLE
Advanced examples: $each

### ISSUE THREAD

**Issue by lorro** [dobromir-hristov/vuelidate-error-extractor#20]
Hi,

I'm trying to implement a similar setup as in the advanced examples. I have an array of objects I need to validate. But I can't manually set the form-group name. This should be dynamic as the form-group is part of vuetify datatable "items" slot.

When I do this the validation seems to work: 
```js
<form-group :name="countedTotals.$each.0.amount" slot="activator">
```

Though when I would change it to this nothing happens:
```js
<form-group :name="`countedTotals.$each.${props.item.id}.amount`" slot="activator">
```

Any ideas?

Thanks!

**Comment by lorro** [comment]
Seems I managed to fix it by just using the "index" prop of the "items" slot instead of the id of each item.
```js
<form-group :name="`countedTotals.$each.${props.index}.amount`" slot="activator">
```

**Comment by dobromir-hristov** [comment]
Hi. Sorry for not responding sooner, I totally got carried away. Correct. $each is an array of items.
