### ISSUE TITLE
Vuelidate requiredIf validation doesn't work.

### ISSUE THREAD

**Issue by Prashanth-Primaseller** [dobromir-hristov/vuelidate-error-extractor#24]
### vue & vuelidate-error-extractor version
2.4.0

I am using vuelidate-error-extractor with Buefy and it works great.
But I am facing an issue with requiredIf validation. Please refer the below codepen.

https://codepen.io/prashanth-primaseller/pen/qwErRx

requiredIf takes in arguments to return a Boolean which it does and even the validations occur.
Itseems vuelidate-error-extractor doesn't consider the `required:requiredIf()` notation.

I just started using the library and I am stuck at this point. Could you please assist with this?

**Comment by louisboulagnon** [comment]
Hey, this isn't a vuelidate-error-extractor bug, nor does it appear to be a bug at all for that matter, but rather a design choice.

`requireIf` calls the `ref` helper, which you can find [here](https://github.com/vuelidate/vuelidate/blob/66265fe4a1a30208be177901a568fb571f766f86/src/validators/common.js#L38)

What it does is: if the prop you passed is a function, it evaluates it with parentVm as only param and your component as the context (so you can use `this` inside the function).
If the prop you passed is anything but a function, it will try to access parentVm[prop].

In your case, `requiredIf` tries to access `parentVm[true]` which is undefined therefore the condition is not required. If you debug $v, you'll see that the requiredIf validation is never false (no error), so vuelidate-error-extractor doesn't pick it up.

In your example, it should have been `requiredIf(()=>true)`  to always be required.
NB just in case, don't use arrow function if you want to use the component context inside the function ;)

Hope this helps

**Comment by dobromir-hristov** [comment]
You are using the validator wrongly, as @louisboulagnon explained. Closing this.
