### ISSUE TITLE
Use template engine that supports nested objects

### ISSUE THREAD

**Issue by mokkabonna** [dobromir-hristov/vuelidate-error-extractor#3]
Would you be willing to change the template engine you are currently using to one that supports nested objects? Or at least property names with a dot in them?

I have created this plugin: https://github.com/mokkabonna/vue-vuelidate-jsonschema

It exposes to **$params** the schema that belongs to the property:

```js
schemaPattern: {
  schema: {
    type: 'string',
    title: 'Name',
    description: 'The name of the student.',
    pattern: '^\\w+\s\\w+$',
    default: 'Jack'
  }
}
```

But I can't reference it in the message templates since **string-template** does not support nested objects. Or object names with dots in them. There is a PR open to https://github.com/Matt-Esch/string-template/pull/19 fix that, but it's quite old.

One option is https://www.npmjs.com/package/es6-template-strings

**Comment by dobromir-hristov** [comment]
I used the `string-template` library as I wanted the templates to be the same format as the ones that vue-i18n supports - with a single curly bracket. I will search for another plugin that uses that style.
Changing to es6-template-strings would mean a breaking change as current templates wont be supported any more.

**Comment by dobromir-hristov** [comment]
https://github.com/sindresorhus/pupa
https://www.npmjs.com/package/micromustache - Not the same syntax, but supports all kinds of deep access, arrays, objects etc.

**Comment by dobromir-hristov** [comment]
@mokkabonna Tried pupa today and it has deep nesting and seems to work OK. Will do a release today with some changes to the template naming, as well as some new helper functions.

Will start adding proper tests after that.

**Comment by mokkabonna** [comment]
Sounds good, thanks!

**Comment by dobromir-hristov** [comment]
@mokkabonna try it and tell me if you find issues.

**Comment by mokkabonna** [comment]
That seems to be working just as expected, thanks. Tested with deep nesting. Closing.

**Comment by dobromir-hristov** [comment]
Yep :) No need to for now. Will clean it up a bit when I get more time.
