### ISSUE TITLE
Compatibility with Vuelidate v2?

### ISSUE THREAD

**Issue by mycarrysun** [dobromir-hristov/vuelidate-error-extractor#47]
Wondering if compatibility for v2 is on the roadmap for this project or if I should just create my own error extractor hook to replace the mixins here

**Comment by dobromir-hristov** [comment]
What do you think this plugin should do for v2? Error messages are baked into validators in v2, so the main problem it was solving is no longer there.

**Comment by mycarrysun** [comment]
Ah nice - yea I was working on a project last night and it was erroring out on getting the `$params` key for a validator passed into the form group which I don't think exists on all validators anymore so thought there would need to be some refactoring to account for breaking changes. I will close this issue.
