### ISSUE TITLE
Computed property for nested errors

### ISSUE THREAD

**Issue by cypressious** [dobromir-hristov/vuelidate-error-extractor#5]
Have you considered support for nested errors? I'm using https://github.com/mokkabonna/vue-vuelidate-jsonschema, so the `validator` object is pretty messy. It would be nice to have a property similar to `activeErrors` to get all errors including the ones of nested objects.

**Comment by dobromir-hristov** [comment]
I think you can use nested validation messages just by well nesting them and then having the name of each validaiton rule as follows:
```
import {email} from 'vuelidate/lib/validators'
export default {
 // you typical stuff.
  validations: {
    'email.simple': { email }
  }
}

// Somewhere error messages are kept
{
 email: {
   simple: 'Email is bad',
   detailed: 'The email field is not valid. Please bla bla bla'
}
}
```
