### ISSUE TITLE
Expected a string in the first argument, got undefined

### ISSUE THREAD

**Issue by tribakzero** [dobromir-hristov/vuelidate-error-extractor#6]
I'm currently working with:
vue-cli: 3
vue: 2.5.13
vuelidate-error-extractor: 1.3.1

My problem is that I keep getting: 

> Expected a string in the first argument, got undefined

This is from the `get function` inside `vuelidate-error-extractor.js`
When inspected, string is undefined, object is the object of messages and fallback is false.

This happens every time I try to submit the form, It may be related to the nested structure of my data or that I don't have a validation for address but for it's children... I'm not sure.

Here is a copy of my messages, data and validations.

```
  messages: {
    required: 'required field',
    numeric: 'numeric field'
  }
```

```
  user: {
    number: null,
    address: {},
    another: null
  }
```

```
  validations: {
    user: {
      number: { numeric },
      address: {
        line_1: {
          required
        },
        number: {
          required,
          numeric
        }
      },
      another: {}
    }
  }
```

**Comment by dobromir-hristov** [comment]
It is totally fine to not have validation for address, but you should really add `number` and `line_1` to the `address` data as default states, because you loose reactivity otherwise. 

I tried to reproduce the issue but i cannot. Can you please create a small bin somewhere so I can see the error in action? You can use [codesandbox](https://codesandbox.io/).

**Comment by tribakzero** [comment]
Thanks for the advice, I just copy pasted most of the example I was working on, hope it's not that messy.

https://codesandbox.io/s/vjpzlm4093

As stated before, when I submit, it shows the warning on the console. Also if I add data to `Line 1`, then to `number` and then remove the data from `number` it shows up.

**Comment by dobromir-hristov** [comment]
Hey. I got something here.
Inside `KrgrAddressInput` you had a `form-group` wrapping the other two inputs, but you were feeding it the whole validation object. That doesnt really work that way. I went ahead and just replaced that wrapping `form-group` with a div (as I didnt find a purpose for it) and it all works without any errors.
https://codesandbox.io/s/l55jqv3koq
Try and tell me if it works for you.

**Comment by tribakzero** [comment]
Hey, sorry for not replying earlier, I was able to check the problem only today and as you say, that solved it.
Thanks for helping me, I'm really liking your project, now my components are way cleaner and I have a defined place to add my validation texts.
