### ISSUE TITLE
Feature: Access validation helpers outside of the template

### ISSUE THREAD

**Issue by pareeohnos** [dobromir-hristov/vuelidate-error-extractor#7]
It would be really useful to be able to use the error message helpers outside of the template and just in general usage. 

In the app I'm working on, I would require multiple templates for different parts of the form which is (I believe) not currently support, but even in this scenario it wouldn't be a perfect fit. The form I'm working on has a few normal fields, but then has a table with inputs in each row. This table cannot use the standard template for displaying errors, so instead I have a message above the table which displays a summary of the errors that have occurred within the table.

Currently, I have to aggregate all of the errors within the table to produce an object summarising which validations have failed. From there, I want to then display the error messages using the error extractor, however because this part of the form does not use the template, I don't have access to the helpers. I could include the mixin but this then provides the additional props and other things which I don't have a need for.

Ideally, I would like to be able to simply include the helpers on their own and provide the vuelidate object on which I want the error message, or whatever would be required to get the error messages.

If this is already possible then I apologise for the issue, but I couldn't see anything in the documentation and a quick glance through the code didn't highlight anything obvious

**Comment by dobromir-hristov** [comment]
Try including the mixin only? It will give you all the helpers.

**Comment by pareeohnos** [comment]
When you say include the mixin only, you mean just add

    import { extractorMixin } from 'vuelidate-error-extractor';

or actually bring it in with `mixins: [extractorMixin]`?

**Comment by dobromir-hristov** [comment]
Import the extractorMixin and apply it with `mixins: [extractorMixin]` to your component that needs access to validation helpers.
Essentially recreate the form-input templates

**Comment by dobromir-hristov** [comment]
Well I see two options really. Wait for me to extract the helpers to a file, then you can later solely import them or do it your self and maybe do a PR?

For the most part, you should be able to do this with a simple loop over the validation object and wont need the helpers. They are over complicated because they support attribute remapping and such, which is not needed for your case I presume.

**Comment by pareeohnos** [comment]
Nah I don't need anything complex, I just literally wanna take a failed validation, and get back a message like 'This field is required' so just the translation part really. If this is easy enough without the helpers then I'm happy to go with that, just unsure how to extract that message

**Comment by dobromir-hristov** [comment]
I think you could do `this.$v.yourForm.$flattenParams()` that would return something like this:
```
[
  {
    "path": [
      "yourForm",
      "title"
    ],
    "name": "required",
    "params": {
      "type": "required"
    }
  },
  {
    "path": [
      "yourForm",
      "source_types"
    ],
    "name": "required",
    "params": {
      "type": "required"
    }
  },
  {
    "path": [
      "yourForm",
      "main_search_term"
    ],
    "name": "required",
    "params": {
      "type": "required"
    }
  }
]
```

**Comment by dobromir-hristov** [comment]
But that wont return you the current status of the validator...

**Comment by dobromir-hristov** [comment]
Aha. Yep, that would work. I will extract those funcs into the utils later when I can. 
You could checkout the template function in `utils.js` and use it for replacing `{attribute}`

**Comment by pareeohnos** [comment]
Ah thanks wondered where that was, got confused by the name `template` as I thought that was related to the actual template component. Will have a look now

**Comment by dobromir-hristov** [comment]
I made some progress yesterday but hit a wall. I managed to deeply extract all validation objects along with their params and error statuses, but because I dont have the label of each one, I cant format the error messages. I am missing the `{attribute}`. 

It would be up to you to figure out if `some.deep.nested.value` should be called `User address`. I could accept an object of `validated:attribute` properties like:
```js
{
   username: 'Username'.
   email: 'Email',
   'addresses.first_address': 'First Address'
}
```
Then i can map the validation props and insert the `attribute` to the `params` for each error message. 
I will most probably make this into a vue component that you import and pass the validator and because its in the Vue scope it will have access to i18n, messages etc.

**Comment by pareeohnos** [comment]
I could see the benefit of having the attribute names stored in a global object similar to how the messages are. Then as you say it would be easy to localise these with i18n. It would also be great not having to pass the `attribute` prop to each component, might simplify things somewhat.

**Comment by dobromir-hristov** [comment]
That wont help with passing the attribute every time as I dont have access to the name of the prop you are validating per field.

**Comment by pareeohnos** [comment]
ah ok makes sense.

**Comment by dobromir-hristov** [comment]
A total rewrite of the plugin is on its way. It will allow for multiple error extraction (form summary) single error display and more.
As for helpers, those are inside a utils file so they could get loaded if needed.

**Comment by pareeohnos** [comment]
Ah awesome, sounds perfect!

**Comment by dobromir-hristov** [comment]
Closing this as v2 now has summary error display.

**Comment by pareeohnos** [comment]
Taken a quick look, looks as though the `flattenValidatorObjects` is the culprit. It doesn't go any deeper than the immediate level of of the validator object, whereas in my use-case, the `lineItems` property is a list of things so I may have to stick with my original code

**Comment by dobromir-hristov** [comment]
I actually does. Will need to see a sample of your data structure.

**Comment by pareeohnos** [comment]
If it's possible to make it traverse nested validators, it would be useful to make it an optional flag. The form I'm building displays a summary in two parts - one at the top for the direct child validators of the form object, and one that summarises the errors in the line items table. If it were to traverse all the nested errors then the top level summary would include errors for line items which I wouldn't want, but the summary above the line items table would need to traverse.

Hope that makes sense? Equally if it's not something you want added to the library then that's not a problem. The summary stuff that's there is working for the rest of the form so it's still a brilliant addition, so thanks for the fantastic work and quick turn around!

**Comment by pareeohnos** [comment]
Sorry didn't see your response. My data looks a bit like this:

```javascript
{
  invoice: {
     name: "",
     number: "",
     lineItems: [{
        quantity: 0,
        description: ""
      }]
  }
}
```

And the validations like so

```javascript
invoice: {
  name: { required },
  number: { required },
  lineItems: {
    $each: {
      quantity: { decimal, required },
      description: { required }
    }
  }
}
```

I did a quick test and it seemed as though it was just filtering out all non `$` keys, but the validator didn't seem to have a `lineItems` key so it never tried it

**Comment by dobromir-hristov** [comment]
I be damned... 😆 I forgot about $each usage. Will come with a fix later today.

**Comment by pareeohnos** [comment]
haha ok I'm not going mad then :D awesome thanks, will clean up my code quite a bit I think :)

**Comment by dobromir-hristov** [comment]
Currently we are resolving the names of each nested field by trying to map its `form.property` to the `attributes` object. For nested i used to do `parent.child.grandchild` now it would be `parent.child.[index].grandchild`. I can either use just the grandchild name or try to skip numeric indexes so its same as above.

**Comment by pareeohnos** [comment]
Whichever works really. I guess you could use the `parent.child[index].grandchild` and just access a single index, but that method may break if there are no child records? If for instance you have children with the `name` required, but there are no child entries, would this fail?

**Comment by dobromir-hristov** [comment]
Alright so I got this working.

Problem with naming the bloody nested elements still persists. Currently I have this:
```js
nestedForm: {
      phones: {
        $each: {
          model: { required },
          brand: { minLength: minLength(8) }
        }
      }
    }
```
Now how should we define the model and the brand inside the `attributes` object upon init, so it can auto extract their names.

The name for each field by default now is
`phones.$each.0.model`
`phones.$each.1.model`

etc...

We could rework it so it skips the numeric index like:

`phones.model`
`phones.$each.model`
`phones.[].model`
`model`

Now the other issue is, how to tell the user which field exactly has the issue. I would probably have to pass the position of the currently validated field in the `$each` array, but that is not easy, especially if nested more than once. The error message would also look strange.

`The phone model is required for field 5` or something like that.

**Comment by dobromir-hristov** [comment]
OK so I got an idea. 

Inside the `attributes` setting, you define nested fields like so:
```js
{
   email: 'Email',
   'phones.model': 'Phone Model',
   'phones.brand': 'Phone Brand'
}
```

Error extractors go through `$each` validator errors that and try to match `phones.$each.0.model` to `phones.model`. This is to be able to extract proper field name (attribute prop) everywhere.

However, when using with singleErrorExtractors, the user will have to pass `phones.$each.0.model` in the `name` prop, so the appropriate field errors can be shown. Users should be able to construct this string by knowing the index of the current field any way.

**Comment by pareeohnos** [comment]
ah that seems to be working now! Great stuff. Is there a way of not repeating error messages? So if for instance in your example, you had 5 phones and 4 of them didn't have a `model` assigned, is there a way of having it just display the error once instead of 4 times? I assume with a custom `form-errors` component this would work?

**Comment by dobromir-hristov** [comment]
Hmmm. You have to filter them somehow. 

One way of doing this would be to create a computed property that uses filters out the repetitions in the array of errors. You can filter the ready `activeErrorMessages` as strings because if two strings are the same, you want just one. Try lodash `uniq` :)

**Comment by pareeohnos** [comment]
That works, will give that a go. Thanks for the quick turn around on this, seems to be working brilliantly :)

**Comment by pareeohnos** [comment]
Sorry for the huge delay but I got this working. Just created a custom component extending the `multiErrorExtractorMixin` and displaying only unique errors. Works perfectly.

Thanks again for the work on this!
