### ISSUE TITLE
Bootstrap 4 support?

### ISSUE THREAD

**Issue by JasonHenson** [dobromir-hristov/vuelidate-error-extractor#9]
Any plans to support Bootstrap 4 in the very near future?

**Comment by dobromir-hristov** [comment]
Looking at Bootstrap 4, this is a normal field after validation
```vue
<div class="col-md-6 mb-3">
      <label for="validationServer03">City</label>
      <input type="text" class="form-control is-invalid" placeholder="City" required>
      <div class="invalid-feedback">
        Please provide a valid city.
      </div>
</div>
```
We can have the `invalid-feedback` and the label, but we cannot add the `is-invalid` class to your inputs, as those will be provided via slots. Do you think this would be sufficient?

**Comment by JasonHenson** [comment]
That should be fine. Thanks for the quick response!

**Comment by dobromir-hristov** [comment]
```vue
 <form-wrapper :validator="$v.form">
    <form-group name="email">
      <template slot-scope="{ validator, hasErrors }">
        <input
          class="form-control"
          :class="{ 'is-invalid': hasErrors, 'is-valid': !hasErrors }"
          type="email"
          name="email"
          @input="validator.$touch()">
      </template>
    </form-group>

    <form-group name="name">
      <template slot-scope="{ validator, hasErrors }">
        <input
          class="form-control"
          :class="{ 'is-invalid': hasErrors, 'is-valid': !hasErrors }"
          type="text"
          name="name"
          @input="validator.$touch()">
      </template>
    </form-group>
  </form-wrapper>
```
This is an example how you can add `is-valid` and `is-invalid` classes to your inputs. Its a bit more boilerplate than I would like to, but its either this, or rendering an input for you (which i will not do).

**Comment by dobromir-hristov** [comment]
Alright. Managed to remove some boilerplate. I think this 
```vue
<form-group name="first_name">
     <template slot-scope="{ attributes, events }">
          <input
            v-bind="attributes"
            v-on="events"
            type="text"
            v-model="nestedObject.first_name">
     </template>
</form-group>
```

**Comment by JasonHenson** [comment]
The last example looks much cleaner for sure. I wouldn't want to have the input rendered anyways as I use bootstrap-vue component. I really appreciate you working on this so fast.

**Comment by dobromir-hristov** [comment]
@JasonHenson try now :)

**Comment by JasonHenson** [comment]
thank you it is adding support so fast -- it is adding the correct classes now!

Unrelated question, do you have any plans to support Bootstrap-vue? I have to use a non-component form-group, etc. to get validation to function correctly.

https://bootstrap-vue.js.org/

**Comment by dobromir-hristov** [comment]
Hey @JasonHenson I looked at bootstrap-vue and you can totally use their formgroup. Just wrap it with your component that renders the form-group and passes the invalid-state to it.
Something like this:
```vue
<template>
  <b-form-group
    :invalid-feedback="firstErrorMessage"
    :state="isValid"
  >
    <slot
      :state="isValid"
    />
  </b-form-group>
</template>
<script>
import { singleErrorExtractorMixin } from 'vuelidate-error-extractor'

export default {
  name: 'FormElement',
  extends: singleErrorExtractorMixin
}
</script>
```

**Comment by dobromir-hristov** [comment]
I wrote this without testing at all, but I think it should work :)

**Comment by paolog22** [comment]
thanks very fast response <3 . one more thing base on the code above .. state is false but the input is red.. i dont know why..

**Comment by dobromir-hristov** [comment]
if state is false, it will be red. That would mean the isValid property in the error extractor is returning false.

**Comment by paolog22** [comment]
ow my bad.. sorry .. thanks :) hope to see more supported framework like bootstrap-vue :)

**Comment by dobromir-hristov** [comment]
Well I have tried with Quasar and Bulma and it works perfectly. Maybe I should make a page on how to use them...

**Comment by paolog22** [comment]
@dobromir-hristov please do :) that would be very helpful

**Comment by paolog22** [comment]
please when you do the page please make initial state to null :) if possible thanks

**Comment by dobromir-hristov** [comment]
Is it always green atm ?

**Comment by paolog22** [comment]
always red ..

**Comment by dobromir-hristov** [comment]
<template>
  <b-form-group
    :invalid-feedback="firstErrorMessage"
    :state="formGroupState "
  >
    <slot
      :state="formGroupState "
    />
  </b-form-group>
</template>
<script>
import { singleErrorExtractorMixin } from 'vuelidate-error-extractor'

export default {
  name: 'FormElement',
  extends: singleErrorExtractorMixin,
 computed: {
     formGroupState () {
       return this.preferredValidator.$dirty ? this.isValid : null
     }
  }
}
</script>

**Comment by paolog22** [comment]
that is working.. thank you :)

**Comment by dobromir-hristov** [comment]
Will update it with next release.

**Comment by JasonHenson** [comment]
Hey, sorry for the delay -- I was able to get your example working. Thank you!

**Comment by paolog22** [comment]
please include vuetify too when you have time thanks :)

**Comment by dobromir-hristov** [comment]
@paolog22 done. https://dobromir-hristov.github.io/vuelidate-error-extractor/other_frameworks.html#usage-with-vuetify

**Comment by paolog22** [comment]
Wow.. thank you. I got it working with vuetify from your previous example, but i think this is better :) thank you

**Comment by dobromir-hristov** [comment]
Example is added to the docs now.
https://dobromir-hristov.github.io/vuelidate-error-extractor/other_frameworks.html#usage-with-bootstrapvue
